tarantool/httpng

CMakeLists.txt
Wslay cmake config creates wlayver.h file in build-tree.
So, if to run cmake in build/ directory wslayver.h will
be created in build/*/wslay/include which is unknown for
libh2o at build stage.
Fixes #1
=> fix 'wslay/wslayver.h file not found'

httpng/httpng.c
Field was initialized too late - HTTP server thread raced with
TX thread which caused crash due to choosing wrong code path
=> fix crash under load

.gitmodules
Changed URL of wslay to tarantool fork repo.
Closes #14
=> Fork wslay and change submodule URI

httpng/httpng.c, tests/bad_handlers.lua
The following functions now properly report errors:
payload_writer_write() AKA io:write()
header_writer_write_header() AKA io:write_header()
close_lua_req() AKA io:close()
header_writer_upgrade_to_websocket() AKA io:upgrade_to_websocket()
websocket_send_text() AKA ws:send_text()
close_lua_websocket() AKA ws:close()
get_query() AKA req:query()
get_query() now checks query_at for sanity.
Added tests for most of these error checks.
Part of #7
=> add error handling to HTTP request handler functions

httpng/httpng.c, tests/shuttle_size.lua
Existing "saturating" checks for MIN/MAX allow small shuttle_size
which may be enough for some C handlers but not for Lua handlers.
Part of #7
=> check shuttle_size is large enough for Lua handlers

httpng/httpng.c
SSL and TLS 1.0/1.1 are officially deprecated at the moment
=> disable ssl/tls older than tls 1.2

CMakeLists.txt, asan/asan.supp
This obviously requires tarantool binary itself to be built with
enabled ASAN.
CC=clang CXX=clang++ cmake -DENABLE_ASAN=ON .
=> asan can be enabled

httpng/httpng.c, tests/wrong_config.lua
Use min_proto_version which defaults to 'tls1.2'
=> min allowed ssl/tls proto is now configurable

httpng/httpng.c, tests/wrong_config.lua
openssl_security_limit, defaults to 1 (which is typical default
for OpenSSL),
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html
Now you can benchmark certificates with small RSA keys as much
as you want or tighten security to the sky.
=> openssl security level is configurable

httpng/httpng.c
fix uninitialized variable
Caught when building on macOS:
```
$ make -j
...
[100%] Building C object CMakeFiles/httpng.dir/httpng/httpng.c.o
/Users/a.starshov/httpng/httpng/httpng.c:1572:6: error: variable 'thread_ctx' is used uninitialized whenever 'if' condition is true
[-Werror,-Wsometimes-uninitialized]
if (fill_received_headers_and_body(L, shuttle)) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/a.starshov/httpng/httpng/httpng.c:1643:8: note: uninitialized use occurs here
if (--thread_ctx->active_lua_fibers == 0 &&
^~~~~~~~~~
/Users/a.starshov/httpng/httpng/httpng.c:1572:2: note: remove the 'if' if its condition is always false
if (fill_received_headers_and_body(L, shuttle)) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/a.starshov/httpng/httpng/httpng.c:1596:2: …
```
=> fix libh2o-evloop build and unutilized variable

httpng/httpng.c
Now in case of initialization error we wait for TX fibers to exit
before deallocating memory.
Part of #6
=> fix use-after-free on initialization error

httpng/httpng.c
Listening socket struct was freed before thread has finished.
Part of #6
=> fix use-after-free on shutdown

examples/multiple.lua, httpng/httpng.c
N. b.: there are still stability issues, especially if evloop is used
(and it is used by default). There is also file descriptor leak issue
which is visible when HTTP server is shut down and launched again
numerous times.
examples/multiple.lua now does exactly that.
Part of #6
=> shutdown is now available as lua function

httpng/httpng.c, httpng/httpng_sem.h
macOS Catalina 10.15.7:
```
$ make
...
Scanning dependencies of target httpng
[100%] Building C object CMakeFiles/httpng.dir/httpng/httpng.c.o
/Users/a.starshov/httpng/httpng/httpng.c:2472:2: error: 'sem_destroy' is deprecated [-Werror,-Wdeprecated-declarations]
sem_destroy(&thread_ctx->can_be_terminated);
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been
explicitly marked deprecated here
int sem_destroy(sem_t *) __deprecated;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/cdefs.h:196:40: note: expanded from macro
'__deprecated'
#define __deprecated    __attribute__((__deprecated__))
^ …
```
=> add cross-platform semaphores

CMakeLists.txt, httpng/fd-leak-detector.cpp, httpng/fd-leak-detector.h, httpng/httpng.c
Tested on Ubuntu 20.04.
Compatibility issues likely.
Would not detect leaks inside libuv unless it is built from source
(it does not at the moment).
Part of #6
=> add simple file descriptor leak detector engine

examples/benchmark_query.lua, examples/multiple.lua
=> disable write ahead logs for examples

examples/hot_reload_handler.lua, httpng/httpng.c
cfg() can be called w/o calling shutdown(), it would replace
Lua handler (only for "/" and only if it is specified as "handler"
and not in "sites" array). Everything else is ignored and not even
checked for sanity.
Part of #18
=> hot reload prototype (handler only)

httpng/httpng.c
Older versions printed warning to console, now this is done only when
called as on_shutdown().
Part of #6
=> shutdown() returns error if already in progress

examples/hot_reload_multi_handler.lua, httpng/httpng.c
Hot reload code is now integrated into cfg(), this way there is less
copy-paste and we can check everything for sanity (not everything is
checked yet for easier merging). All Lua handlers are now replaced but
this is not being done atomically or efficiently.
Some parameters from new configuration are used before everything is
checked for sanity (to be improved later).
Also fixed some memory/resource leaks when initialization fails due to
invalid parameters.
Part of #18
=> hot reload for all lua handlers

httpng/httpng.c
Such connections must be treated differently from "regular" HTTP 1.x
Part of #6
=> fix crash on shutdown w/alive websocket connections

examples/multiple.lua
Older Firefox version have bug which results in periodic timer not
being cancelled, worked around that.
Part of #100
=> workaround for websockets example app

httpng/httpng.c
It would have caused problems with multilisten.
Part of #2
=> fix using '0' index in one of loops processing listeners

tests/all.lua
listen(80) works on MacOS w/o root, this also disrupts other tests
because httpng.shutdown() was not called. Removed.
Part of #13
=> tests: remove 'listen(80)'

examples/files1/hello.txt, examples/files2/hello.txt, examples/native_files.lua, httpng/httpng.c, tests/all.lua
API is still old "sites" (to be replaced).
Folders only, not individual files.
Not configurable - no MIME types, compression, ETag...
Shutdown and hot reload work but you can't replace Lua handler with
native Lua handler and vice versa, remove path first.
Part of #38
=> libh2o native file hosting (prototype)

.gitmodules, CMakeLists.txt
It seems unused (at least for now). So let's just drop this submodule.
=> build: drop unused msgpuck submodule
