- httpng/httpng.c
> fix uninitialized variable 

- README.md
- examples/benchmark_hello.lua
- httpng/httpng.c
Listen 0.0.0.0, compilability as Release (w/o assert()),
example benchmark handler
> minor changes to be able to benchmark

- examples/benchmark_query.lua
- examples/multiple.lua
- httpng/httpng.c
API is compatible with tarantool/http
Part of #31
> lua handlers: add req:query()

- httpng/httpng.c
- tests/wrong_config.lua
Added luatest to ensure wrong configuration parameters
are properly reported.
Part of #7
> cfg(): report errors and free resources

- httpng/httpng.c
> print warning when adjusting params for min/max

- README.md
> correct readme (error checking)

- httpng/httpng.c
Listening sockets are closed, existing TCP connections are
terminated, threads and fibers are gracefully terminated,
resources are deallocated.
Also:
WebSockets no longer deadlock (leak fiber) on cancellation.
Limited number of connections when libuv is used
(only evloop version had such check before).
Fixed several issues with resources deallocation
when initialization failed.
Part of #6
> implement shutdown

- httpng/httpng.c
shuttle_t was freed by TX thread on request cancellation (TCP connection
close) while it could still be queued for processing by HTTP thread in
xtm queue (race). Now susceptible shuttle_t frees are performed by
queueing such requests to HTTP thread - it would happen after already
queued requests.
Part of #6
> fix use-after-free on req cancellation

- httpng/httpng.c
Parts of initialization/deinitialization code moved to HTTP thread
because h2o uses thread-local variables.
Part of #6
> fix stability issues with shutdown

- httpng/httpng.c
Also fixed incorrect deinitialization
Part of #6
> fix race on shutdown

- httpng/httpng.c
Unfortunately we can't reliably use read callback to gracefully
terminate HTTP/HTTPS TCP connections because such callback pointer
can be NULL (rarely for HTTPS, frequently for HTTP).
Now we check current connection type and call h2o internal functions
(h2o has been modified to implement this).
Part of #6
> fix crash on shutdown

- httpng/httpng.c
- tests/shutdown.lua
> do not allow shutdown() w/o cfg(), double cfg()

- httpng/httpng.c
> clean up dead code

- httpng/httpng.c
> fix resources/memory leak

- tests/shutdown.lua
> more shutdown tests

- httpng/httpng.c
> fix deadlock on second and following shutdowns

- httpng/httpng.c
> fix descriptor leak when using libuv

- httpng/httpng.c
> fix file descriptor leak when using evloop

- httpng/httpng.c
No more warnings printed as a result
Part of #6
> properly unregister on_shutdown handler

- examples/benchmark_query.lua
- examples/multiple.lua
> disable checkpointing for examples

- httpng/httpng.c
> hot reload no longer applies configuration partially

- httpng/httpng.c
> fix compilability on centos7

- tests/shutdown.lua
- tests/wrong_config.lua
> adjust shutdown tests for hot reload capability

- httpng/httpng.c
It is also checked that all sites are specified for reconfiguration.
Part of #18
> hot reload all handlers at once

- httpng/httpng.c
- tests/all.lua
> add hot reload tests and fix found issues

- tests/all.lua
> more hot reload tests

- httpng/httpng.c
- tests/all.lua
h2o contexts has been made per-thread for this to work.
Note that '/' for now can only be added as
"sites[...] = {path = '/' handler = ...}" but not as "handler = ..."
Part of #18
> hot reload can add new paths

- httpng/httpng.c
- tests/all.lua
> hot reload can add primary handler

- httpng/httpng.c
- tests/all.lua
> hot reload can add paths "after" root

- httpng/httpng.c
- tests/all.lua
> do not allow duplicate paths

- httpng/httpng.c
- tests/all.lua
> hot reload can remove paths

- httpng/httpng.c
> minor refactoring

- httpng/httpng.c
- tests/all.lua
> fix crash after decreasing number of threads

- tests/all.lua
> add hot reload decrease threads test

- httpng/httpng.c
> decreasing threads not waking fiber unnecessarily

- httpng/httpng.c
> minor refactoring: make cfg() shorter

- httpng/httpng.c
- tests/all.lua
> add force_decrease_threads() api

- httpng/httpng.c
Added a single interfaces to register and close, start read, stop read,
listener sockets.
It helps to manipulate by listener sockets better in single place.
Also, added closing sockets in some places where it should be.
> add interface for creating and closing listeners

- httpng/httpng.c
- tests/all.lua
> hot reload: fix issues found with added tests

- httpng/fd-leak-detector.cpp
- httpng/fd-leak-detector.h
> update h2o (fixed epoll leaks) and detect such leaks

- httpng/httpng.c
> hot reload: fix removing root

- httpng/httpng.c
- tests/all.lua
> hot reload: configurable timeout for decreasing threads

- httpng/httpng.c
One change is refactoring/foolprofing, everything else is just working
around gcc trying to be static analyzer but not being smart enough to
analyze ifs/loops/goto.
Not a hot path, not a problem.
No actual logic changes.
Closes #137
> fix building as release

- tests/all.lua
> make tests/all.lua groups global for easier debugging

- README.md
- doc/api.md
> add api documentation

- doc/api.md
> doc: more api details

- README.md
- doc/api.md
> doc: update readme; cosmetics

- doc/api.md
> doc: fix and clarify "headers" logic description

- httpng/httpng.c
- tests/all.lua
Now we have an app... mmm... a test for that!
> fix req:query() throwing error when there is no query

- examples/multiple.lua
- httpng/httpng.c
> add http(s) request info about our own addr/port

- doc/api.md
> doc: additional request fields documented

- httpng/httpng.c
> hot reload: fix crash when adding site

- httpng/httpng.c
It happened if HTTP/2 connections were active.
Make HTTP/2 connections closing truly graceful while we are at it
(already was for HTTP/1.x).
Part of #18
> hot reload: fix crash when decreasing threads

- .github/workflows/build-only.yml
- .github/workflows/with-tests.yml
- tests/all.lua
> run tests twice (and fix them to survive that)

- tests/all.lua
Note that older tests which use wget still use wget defaults
Part of #13
> test http1.x / http/2 separately

- tests/all.lua
> make tests faster (shorter timeouts etc)

- tests/all.lua
> tests: minor refactoring (foolproofing, anti-copy-paste)

- tests/all.lua
Skip corresponding tests instead of failing them.
Only one test would fail now if curl does not support http/2.
Part of #13
> tests: better handle missing http/2 support in curl

- tests/all.lua
> tests: http in addition to https (not all tests yet)

- tests/all.lua
> add tests for insecure http

- tests/all.lua
> tests: properly test insecure/tls for add dup paths

- .github/actions/build-httpng/action.yml
- .github/actions/build-tarantool/action.yml
- .github/workflows/with-tests.yml
> tests: use asan (unconditionally)

- httpng/httpng.c
> add error injection for shutdown and lua api for it

- httpng/httpng.c
- tests/all.lua
And add a test for that.
Part of #18
> hot reload: fix crash on some initialition errors

- httpng/httpng.c
- tests/all.lua
Use-after-free and other special effects.
Add a test for that.
Part of #18
> hot reload: fix error handling

- tests/all.lua
Note that some tests are intentionally not skipped in that case
to make current implementation issues visible.
Part of #13
> tests: skip complex ones when shutdown does not work

- .github/actions/build-tarantool/action.yml
- .github/workflows/build-only.yml
> tests: build and test on tarantool 1.10 and 2.7

- doc/api.md
- httpng/httpng.c
- tests/all.lua
> rename "shuttle" field to "_shuttle"

- doc/api.md
- examples/benchmark_query.lua
- examples/multiple.lua
- httpng/httpng.c
- tests/all.lua
> adjust api for query, peer for tarantool/http v1 compatibility

- httpng/httpng.c
- tests/all.lua
Use-after-free and other special effects.
Add a test for that.
Part of #18
> hot reload: another fix for error handling

- .github/workflows/with-tests.yml
> tests: shuffle

- httpng/httpng.c
> hot reload: minor refactoring - readability/performance

- httpng/httpng.c
Some checks were skipped on hot reload until multilisten support
is merged.
Part of #18
> hot reload: check all parameters (except "listen") for sanity

- tests/all.lua
> tests: tweak flaky one

- httpng/httpng.c
Refactor and optimize corresponding code while we are at it.
> fix cancellation (tcp connection closing) handling

- tests/all.lua
> tests: http(s) request cancellation (tcp connection close)

- .github/workflows/with-tests.yml
- doc/api.md
- httpng/httpng.c
- tests/all.lua
- tests/mangle_etc_hosts.sh
> add virtual host name to request information

- httpng/httpng.c
- tests/all.lua
Calling io:write_header() and io:write() with is_last==true
also avoided this problem because they closed request.
Added a test for this.
> fix deadlock if handler returned nil and didn't close

- tests/all.lua
> tests: behavior of io:write() after io:write(is_last==true)

- tests/all.lua
> tests: tweak flaky ones

- .github/workflows/with-tests.yml
> tests: cosmetics

- README.md
- doc/api.md
Added api for `listen` to `doc/api.md`.
> doc: add listen api

- .github/workflows/with-tests.yml
> tests: also without asan

- .github/workflows/with-tests.yml
> tests: build httpng with asan

- .gitignore
- CMakeLists.txt
- tests/all.lua
- tests/process_helper.c
Note that some minor checks are skipped in that case,
to be worked on later.
Part of #13
> tests: can work w/o popen module (old tarantool)

- CMakeLists.txt
- tests/tests_helper.sh
> tests: add "make test"

- tests/all.lua
> tests: add comment for assert() in flaky test

- httpng.lua
- httpng/httpng.c
- tests/all.lua
Some combo tests had to be removed as incompatible with new hot reload
approach.
Part of #18
> hot reload: check everything for sanity

- httpng/httpng.c
- tests/all.lua
> hot reload: box.NULL to use default parameter value

- httpng/httpng.c
Note that libh2o still does that all the time.
> no longer terminate on failed malloc

- tests/all.lua
> hot reload: reload handler file test/example
